In [22]:
## NumPy Learning

import numpy as np  # importing the numpy library and giving it an alias 'np' for easier reference in the code.
list1 = [1, 2, 3, 4, 5]
arr = np.array(list1)
arr1= np.array([4, 5, 6])
arr2= np.array([[1, 2, 3], [4, 5, 6]])
arr3= np.array([[[1, 2, 3], [4, 5, 6]],[ [7, 8, 9],[11,12,13]]])
print("1D Array:", arr)
print("Array 2 :", arr1)
print( "2D Array: \n",arr2[1,0])
print("3D Array: \n",arr3)
print(arr3[1,0,2])  # accessing the element at index [1,0,2] in the 3D array

print(np.ndim(arr3))    # gives the number of dimensions of the array

print(arr.size)  # gives the total number of elements in the array
print(arr1.size)
print(arr2.size)
print(arr3.size)

print(arr.shape)  # gives the shape of the array (number of rows, number of columns)
print(arr2.shape)
print(arr3.shape)

1D Array: [1 2 3 4 5]
Array 2 : [4 5 6]
2D Array: 
 4
3D Array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
9
3
5
3
6
12
(5,)
(2, 3)
(2, 2, 3)


In [ ]:
# Check if the array in Palindrome
arr4 = np.array([1, 2, 3, 2, 1])
is_palindrome = np.array_equal(arr4, arr4[::-1])  # checks if the array is equal to its reverse
print("Is arr4 a palindrome?", is_palindrome)

Is arr4 a palindrome? True


In [35]:
arr = np.array([0, 2, 3, 4, 5], dtype=float)  # creating a NumPy array with specified data type
print("Original array:", arr)
print(arr+2)
print(arr-2)
print(arr*2)


Original array: [0. 2. 3. 4. 5.]
[2. 4. 5. 6. 7.]
[-2.  0.  1.  2.  3.]
[ 0.  4.  6.  8. 10.]


In [48]:
arr1 = np.zeros([5,5])  # creating a 5x5 array filled with zeros
print("Array of zeros:\n", arr1)
arr2 = np.ones([5,5])   # creating a 5x5 array filled with ones
print("Array of ones:\n", arr2)
arr3 = np.full([5,5], 7)
print("Array of sevens:\n", arr3)
arr4 = np.arange(1,10,5)
print("Array of range:\n", arr4)
arr5 = np.eye(5)  # creating a 5x5 identity matrix
print("Identity matrix:\n", arr5)

Array of zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array of ones:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
Array of sevens:
 [[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]
Array of range:
 [1 6]
Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [ ]:
print(np.linspace(1, 10, 5)) # generates 5 evenly spaced numbers between 1 and 10, inclusive.

[ 1.    3.25  5.5   7.75 10.  ]


In [49]:
arr5 = np.array([2,8,5,0,6,9,5,3])  # creates a 3x3 array with random values between 0 and 1
print("Random array:\n", arr5)
print (arr5.max() , " Another way  :" , np.max(arr5))  # prints the maximum value in the array
print (arr5.min())  # prints the minimum value in the array  
print (arr5.mean())  # prints the mean (average) value of the array
print (arr5.sum())  # prints the sum of all values in the array

# Use abs() , Sqrt() , square() , exp() , log() , log10() , sin() , cos() , tan() , arcsin() , arccos() , arctan() , sinh() , cosh() , tanh() , deg2rad() , rad2deg()
print("Squre array : /n", np.square(arr5))
print("Absolute array : /n", np.abs(arr5))
print("Square root array : /n", np.sqrt(arr5))

Random array:
 [2 8 5 0 6 9 5 3]
9  Another way  : 9
0
4.75
38
Squre array : /n [ 4 64 25  0 36 81 25  9]
Absolute array : /n [2 8 5 0 6 9 5 3]
Square root array : /n [1.41421356 2.82842712 2.23606798 0.         2.44948974 3.
 2.23606798 1.73205081]


In [ ]:
import numpy as np
arr= np.array([[1,5],[7,8]])
arr1= np.array([[4,8],[7,2]])

print (arr+arr1)
print (arr@arr1) #Actual Matrix Multiplication
print(np.matmul(arr,arr1))
print (arr*arr1)
print (arr.T)


[[ 5 13]
 [14 10]]
[[39 18]
 [84 72]]
[[ 4 40]
 [49 16]]
[[1 7]
 [5 8]]


In [3]:
print (np.linalg.inv(arr))
print(np.linalg.det(arr1))

[[-0.2962963   0.18518519]
 [ 0.25925926 -0.03703704]]
-47.999999999999986
