## ==============================
## Practice Questions
## ==============================

### 1. Find the shape, size and dimensions of both matrices.

### 2. Perform element-wise addition of A and B.

### 3. Perform element-wise subtraction (A - B).

### 4. Perform element-wise multiplication.

### 5. Perform matrix multiplication using np.matmul().

### 6. Find the transpose of both matrices.

### 7. Find the determinant of matrix A.

### 8. Find the inverse of matrix A (if possible).

### 9. Find the trace (sum of diagonal elements) of both matrices.

### 10. Find the maximum, minimum, mean and sum of matrix A.

### 11. Find the row-wise sum and column-wise sum of matrix B.

### 12. Extract:
###     a) First row
###     b) Second column
###     c) Last row
###     d) Bottom-right element

### 13. Reshape matrix A into a (1,9) array and flatten matrix B.

### 14. Find the eigenvalues and eigenvectors of matrix A.

### 15. Concatenate A and B:
###     a) Horizontally (hstack)
###     b) Vertically (vstack)

In [2]:
import numpy as np

# Matrix A
A = np.array([
    [2, 4, 6],
    [8, 10, 12],
    [14, 16, 18]
])

# Matrix B
B = np.array([
    [1, 3, 5],
    [7, 9, 11],
    [13, 15, 17]
])

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)


Matrix A:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]

Matrix B:
 [[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]


In [3]:
print(A.shape)
print(B.shape)
print(A.size)
print(B.size)
print(np.ndim(A), " ", A.ndim)
print(np.ndim(B))

(3, 3)
(3, 3)
9
9
2   2
2


In [4]:
print(A+B)
print(A-B)
print(A*B)
print(np.matmul(A,B))
print(A.T)
print(B.T)

[[ 3  7 11]
 [15 19 23]
 [27 31 35]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[  2  12  30]
 [ 56  90 132]
 [182 240 306]]
[[108 132 156]
 [234 294 354]
 [360 456 552]]
[[ 2  8 14]
 [ 4 10 16]
 [ 6 12 18]]
[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]


In [5]:
print(np.linalg.det(A))

-7.612957883143941e-15


In [6]:
print(np.linalg.inv(A))

[[-2.25179981e+15  4.50359963e+15 -2.25179981e+15]
 [ 4.50359963e+15 -9.00719925e+15  4.50359963e+15]
 [-2.25179981e+15  4.50359963e+15 -2.25179981e+15]]


In [7]:
print(np.trace(A))  # Trace GIves the Sum of Diagonal elements
print(np.trace(B))

30
27


In [8]:
print(A.max())
print(A.min())
print(A.mean())
print(A.sum())


18
2
10.0
90


In [9]:
print(B.sum(axis=1))    # Row Wise
print(B.sum(axis=0))    # Column Wise

[ 9 27 45]
[21 27 33]


In [10]:
print(A[0])
print(A[:,1])
print(A[-1])
print(A[-1][-1])

[2 4 6]
[ 4 10 16]
[14 16 18]
18


In [11]:
print(A.reshape(1,9))
print(B.flatten())

[[ 2  4  6  8 10 12 14 16 18]]
[ 1  3  5  7  9 11 13 15 17]


In [12]:
print(np.linalg.eig(A))
print(np.linalg.eig(B))

EigResult(eigenvalues=array([ 3.22336879e+01, -2.23368794e+00, -8.59909594e-16]), eigenvectors=array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))
EigResult(eigenvalues=array([ 2.94452187e+01, -2.44521872e+00,  5.30519989e-17]), eigenvectors=array([[ 0.20079137,  0.79227344,  0.40824829],
       [ 0.5165778 ,  0.09475476, -0.81649658],
       [ 0.83236422, -0.60276391,  0.40824829]]))


In [13]:
print(A)
print(B)

print(np.hstack((A,B)))
print(np.vstack((A,B)))


[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6  1  3  5]
 [ 8 10 12  7  9 11]
 [14 16 18 13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
