In [18]:
## NumPy Learning

import numpy as np  # importing the numpy library and giving it an alias 'np' for easier reference in the code.
list1 = [1, 2, 3, 4, 5]
arr = np.array(list1)
arr1= np.array([4, 5, 6])
arr2= np.array([[1, 2, 3], [4, 5, 6]])
arr3= np.array([[[1, 2, 3], [4, 5, 6]],[ [7, 8, 9],[11,12,13]]])
print("1D Array:", arr)
print("Array 2 :", arr1)
print( "2D Array: \n",arr2[1,0])
print("3D Array: \n",arr3)
print(arr3[1,0,2])  # accessing the element at index [1,0,2] in the 3D array

print(np.ndim(arr3))    # gives the number of dimensions of the array


1D Array: [1 2 3 4 5]
Array 2 : [4 5 6]
2D Array: 
 4
3D Array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]
9
3
